### ISSUE TITLE
burp-server package not managed?

### ISSUE THREAD

**Issue by johnzimm** [vshn/puppet-burp#11]
Just looking over the module and applying to a test box.  It appears ::burp::server doesn't actually manage the installation of the package.

**Comment by andrekeller** [comment]
Which package are you using? We build our own package (https://launchpad.net/~vshn/+archive/ubuntu/backup)  which includes both the client and the server.

**Comment by johnzimm** [comment]
I'm running CentOS 7 and using the EPEL repository.

The two packages for burp in that repo are:

 - burp-client-1.4.40-1.el7.x86_64
 - burp-server-1.4.40-1.el7.x86_64
