### ISSUE TITLE
Adding client config into server node

### ISSUE THREAD

**Issue by kronos-pbrideau** [vshn/puppet-burp#5]
I would like the client to add a custom configuration the server to be put into `/etc/burp/clients/node1.example.com`, precisely:
`restore_client = node2.example.com`

I would add into client.pp:

```
@@ -76,6 +76,7 @@ define burp::client (
   $working_dir = "/var/lib/burp-${name}",
   $clientconfig_tag = undef,
   $configuration = {},
+  $server_configuration = {},
   $cron_minute = '*/15',
   $cron_mode = 't',
   $cron_randomise = '850',
@@ -179,9 +180,10 @@ define burp::client (
       $_clientconfig_tag = $clientconfig_tag
     }
     @@::burp::clientconfig { "${_clientname}-${name}":
       clientname => $_clientname,
       password   => $password,
       tag        => $_clientconfig_tag,
+      configuration => $server_configuration,
     }
```

So in the client, i could add
```
  ::burp::client { 'burp':
    server => $server_backup,
    server_configuration => {
      'restore_client' => 'node2.example.com',
    }
  }
```

Is there another way to do this?  Or would you accept such a PR?

**Comment by tobru** [comment]
This is already possible, just use the `configuration` parameter.

**Comment by kronos-pbrideau** [comment]
Well, using `configuration` add the content on the client side.  `node1.example.com:/etc/burp/burp.conf` like adding: `server_can_restore = 1` on the client.

But this case is adding something on the server side, in `backup.example.com:/etc/burp/clients/node1.example.com`, like adding `restore_client = node2.example.com`

**Comment by tobru** [comment]
Ok, now I see. Feel free to create a PR, I'm happy to merge it.
