### ISSUE TITLE
No files written and no logs?

### ISSUE THREAD

**Issue by SPQRInc** [vshn/puppet-burp#8]
Hello,

I configured BURP as shown in your example.

The clients-directory contains my configured client but my question is now: How can I perform a backup manually and where are the logs located at?

If I run burp -a b on the client itself I just get this:

> root@pp-test:/var/log# burp -a b                     
> root@pp-test:/var/log#

**Comment by tobru** [comment]
This is probably more of a BURP question than a Puppet module question. So the best thing for you would be to read the manual here: http://burp.grke.org/docs.html
You probably want to check the logging configuration in your `/etc/burp/burp.conf`, parameters stdout and syslog
